In [1]:
import pandas as pd

In [2]:
doc1 = []
with open('doc1.txt', 'r') as file:
    for line in file:
        clear_line = line.replace('\n', '').replace(',', '').replace("'", '').strip().lower()
        clear_line=clear_line.replace(',','').replace("\\","").replace("'",'').strip()
        doc1.append(clear_line)
print(doc1)



['widening its probe in the money laundering angle into the death of sushant singh rajput the enforcement directorate (ed) has summoned the personal staff of the late bollywood actor.', 'according to ed sources the financial probe agency has summoned the cook driver and bodyguard of sushant for questioning.', 'the sources said that they have been asked to appear before the agency on thursday. the ed wants to know about the people who visited sushant in the last one year—who all were there at his home; if any meetings took place; and what were the things that were discussed.', 'the agency will also ask them who saw the body of the late actor first after his death.', 'the ed wants to know if financial things were discussed and how was the behaviour of rhea and her family members with the late actor.', 'the ed registered a case of money laundering on july 31 on the basis of the bihar police fir against his girlfriend rhea chakraborty and her family members. the bihar police registered a

In [3]:
doc2 = []
with open('doc2.txt', 'r',encoding='utf8') as file:
    for line in file:
        clear_line = line.replace('\n', '').replace(',', '').replace("'", '').replace(':','').strip().lower()
        clear_line=clear_line.replace(',','').replace("\\","").replace("'",'').strip()
        doc2.append(clear_line)
print(doc2)



['the supreme court will again hear rhea chakraborty’s plea to transfer the fir from bihar police to mumbai police today august 13. on august 11 the second hearing of the case took place wherein the supreme court reserved its verdict after hearing arguments by rhea chakraborty’s lawyer sushant singh rajput’s family lawyer the counsel representing maharashtra government and the solicitor general of india. also read - rhea chakraborty called up aamir khan rana daggubati and other stars claims new reports in sushant singh rajput death case the supreme court asked for brief written notes from all parties by thursday august 13. bihar government files a detailed reply before the supreme court in rhea chakraborty’s petition seeking transfer of fir filed by sushant singh rajput’s father kk singh against her from patna to mumbai. bihar government in its reply claimed that bihar police has jurisdiction to probe the case. also read - aditya thackerays name crops up again in sushant singh rajput d

In [4]:
from string import punctuation
print(punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [5]:
doc11=''
for i in doc1:
    doc11=doc11+i
print(doc11)

widening its probe in the money laundering angle into the death of sushant singh rajput the enforcement directorate (ed) has summoned the personal staff of the late bollywood actor.according to ed sources the financial probe agency has summoned the cook driver and bodyguard of sushant for questioning.the sources said that they have been asked to appear before the agency on thursday. the ed wants to know about the people who visited sushant in the last one year—who all were there at his home; if any meetings took place; and what were the things that were discussed.the agency will also ask them who saw the body of the late actor first after his death.the ed wants to know if financial things were discussed and how was the behaviour of rhea and her family members with the late actor.the ed registered a case of money laundering on july 31 on the basis of the bihar police fir against his girlfriend rhea chakraborty and her family members. the bihar police registered a case on the basis of 

In [6]:
cleaned_doc1=[word for word in doc11.split() if word not in punctuation]


In [7]:
from nltk.corpus import stopwords
stopwords=stopwords.words('english')

In [8]:
final_doc1=[word for word in cleaned_doc1 if word not in stopwords]
doc1_final=''
for i in range(len(final_doc1)):
    doc1_final=doc1_final+' '+final_doc1[i]
print(doc1_final)

 widening probe money laundering angle death sushant singh rajput enforcement directorate (ed) summoned personal staff late bollywood actor.according ed sources financial probe agency summoned cook driver bodyguard sushant questioning.the sources said asked appear agency thursday. ed wants know people visited sushant last one year—who home; meetings took place; things discussed.the agency also ask saw body late actor first death.the ed wants know financial things discussed behaviour rhea family members late actor.the ed registered case money laundering july 31 basis bihar police fir girlfriend rhea chakraborty family members. bihar police registered case basis sushants father k.k. singhs complaint july 25.singh complaint alleged transactions worth rs 15 crore kotak mahindra bank account son unknown bank accounts.the ed till date recorded statement sushants sister mitu singh resides mumbai; rhea father indrajit brother showik sushants ex-manager rheas manager shruti modi sushants hous

In [9]:
doc22=''
for i in doc2:
    doc22=doc22+i
print(doc22)

the supreme court will again hear rhea chakraborty’s plea to transfer the fir from bihar police to mumbai police today august 13. on august 11 the second hearing of the case took place wherein the supreme court reserved its verdict after hearing arguments by rhea chakraborty’s lawyer sushant singh rajput’s family lawyer the counsel representing maharashtra government and the solicitor general of india. also read - rhea chakraborty called up aamir khan rana daggubati and other stars claims new reports in sushant singh rajput death case the supreme court asked for brief written notes from all parties by thursday august 13. bihar government files a detailed reply before the supreme court in rhea chakraborty’s petition seeking transfer of fir filed by sushant singh rajput’s father kk singh against her from patna to mumbai. bihar government in its reply claimed that bihar police has jurisdiction to probe the case. also read - aditya thackerays name crops up again in sushant singh rajput dea

In [10]:
cleaned_doc2=[word for word in doc22.split() if word not in punctuation]


In [11]:
final_doc2=[word for word in cleaned_doc2 if word not in stopwords]
doc2_final=''
for i in range(len(final_doc2)):
    doc2_final=doc2_final+' '+final_doc2[i]
print(doc2_final)

 supreme court hear rhea chakraborty’s plea transfer fir bihar police mumbai police today august 13. august 11 second hearing case took place wherein supreme court reserved verdict hearing arguments rhea chakraborty’s lawyer sushant singh rajput’s family lawyer counsel representing maharashtra government solicitor general india. also read rhea chakraborty called aamir khan rana daggubati stars claims new reports sushant singh rajput death case supreme court asked brief written notes parties thursday august 13. bihar government files detailed reply supreme court rhea chakraborty’s petition seeking transfer fir filed sushant singh rajput’s father kk singh patna mumbai. bihar government reply claimed bihar police jurisdiction probe case. also read aditya thackerays name crops sushant singh rajput death case rhea chakrabortys call log shows au dialled multiple times bihar government’s submission says “there one fir case filed govt. target mumbai police sharing document copy investigation p

In [12]:
from sklearn.feature_extraction.text import CountVectorizer 


In [13]:
doc1_=[]
for i in doc1_final.split():
    doc1_.append(i)
print(doc1_)

['widening', 'probe', 'money', 'laundering', 'angle', 'death', 'sushant', 'singh', 'rajput', 'enforcement', 'directorate', '(ed)', 'summoned', 'personal', 'staff', 'late', 'bollywood', 'actor.according', 'ed', 'sources', 'financial', 'probe', 'agency', 'summoned', 'cook', 'driver', 'bodyguard', 'sushant', 'questioning.the', 'sources', 'said', 'asked', 'appear', 'agency', 'thursday.', 'ed', 'wants', 'know', 'people', 'visited', 'sushant', 'last', 'one', 'year—who', 'home;', 'meetings', 'took', 'place;', 'things', 'discussed.the', 'agency', 'also', 'ask', 'saw', 'body', 'late', 'actor', 'first', 'death.the', 'ed', 'wants', 'know', 'financial', 'things', 'discussed', 'behaviour', 'rhea', 'family', 'members', 'late', 'actor.the', 'ed', 'registered', 'case', 'money', 'laundering', 'july', '31', 'basis', 'bihar', 'police', 'fir', 'girlfriend', 'rhea', 'chakraborty', 'family', 'members.', 'bihar', 'police', 'registered', 'case', 'basis', 'sushants', 'father', 'k.k.', 'singhs', 'complaint', 

In [14]:
vect1 = CountVectorizer()

vect1.fit_transform(doc1_)
print("bag of words :",vect1.get_feature_names())

bag of words : ['14', '15', '25', '31', '34', 'according', 'account', 'accountant', 'accounts', 'accused', 'actor', 'actors', 'agency', 'agencys', 'alleged', 'also', 'angle', 'appear', 'ask', 'asked', 'august', 'bandra', 'bank', 'basis', 'behaviour', 'bihar', 'body', 'bodyguard', 'bollywood', 'brother', 'ca', 'case', 'cbi', 'central', 'chakraborty', 'chartered', 'collected', 'complaint', 'connection', 'cook', 'court', 'crore', 'date', 'dead', 'death', 'decide', 'demanded', 'directorate', 'discussed', 'documents', 'driver', 'ecir', 'ed', 'enforcement', 'ex', 'family', 'father', 'filed', 'financial', 'fir', 'first', 'flat', 'flatmate', 'found', 'girlfriend', 'government', 'hearing', 'home', 'house', 'indrajit', 'july', 'june', 'know', 'kotak', 'last', 'late', 'laundering', 'mahindra', 'manager', 'meetings', 'members', 'miranda', 'mitu', 'modi', 'money', 'mumbai', 'named', 'old', 'one', 'others', 'people', 'personal', 'pithani', 'place', 'plea', 'police', 'probe', 'purnea', 'questioning',

In [15]:
doc2_=[]
for i in doc2_final.split():
    doc2_.append(i)
print(doc2_)

['supreme', 'court', 'hear', 'rhea', 'chakraborty’s', 'plea', 'transfer', 'fir', 'bihar', 'police', 'mumbai', 'police', 'today', 'august', '13.', 'august', '11', 'second', 'hearing', 'case', 'took', 'place', 'wherein', 'supreme', 'court', 'reserved', 'verdict', 'hearing', 'arguments', 'rhea', 'chakraborty’s', 'lawyer', 'sushant', 'singh', 'rajput’s', 'family', 'lawyer', 'counsel', 'representing', 'maharashtra', 'government', 'solicitor', 'general', 'india.', 'also', 'read', 'rhea', 'chakraborty', 'called', 'aamir', 'khan', 'rana', 'daggubati', 'stars', 'claims', 'new', 'reports', 'sushant', 'singh', 'rajput', 'death', 'case', 'supreme', 'court', 'asked', 'brief', 'written', 'notes', 'parties', 'thursday', 'august', '13.', 'bihar', 'government', 'files', 'detailed', 'reply', 'supreme', 'court', 'rhea', 'chakraborty’s', 'petition', 'seeking', 'transfer', 'fir', 'filed', 'sushant', 'singh', 'rajput’s', 'father', 'kk', 'singh', 'patna', 'mumbai.', 'bihar', 'government', 'reply', 'claimed',

In [16]:
vect1.vocabulary_

{'widening': 145,
 'probe': 96,
 'money': 84,
 'laundering': 76,
 'angle': 16,
 'death': 44,
 'sushant': 131,
 'singh': 119,
 'rajput': 99,
 'enforcement': 53,
 'directorate': 47,
 'ed': 52,
 'summoned': 129,
 'personal': 91,
 'staff': 126,
 'late': 75,
 'bollywood': 28,
 'actor': 10,
 'according': 5,
 'sources': 124,
 'financial': 58,
 'agency': 12,
 'cook': 39,
 'driver': 50,
 'bodyguard': 27,
 'questioning': 98,
 'the': 133,
 'said': 109,
 'asked': 19,
 'appear': 17,
 'thursday': 135,
 'wants': 142,
 'know': 72,
 'people': 90,
 'visited': 141,
 'last': 74,
 'one': 88,
 'yearâ': 148,
 'who': 144,
 'home': 67,
 'meetings': 79,
 'took': 137,
 'place': 93,
 'things': 134,
 'discussed': 48,
 'also': 15,
 'ask': 18,
 'saw': 112,
 'body': 26,
 'first': 60,
 'behaviour': 24,
 'rhea': 105,
 'family': 55,
 'members': 80,
 'registered': 103,
 'case': 31,
 'july': 70,
 '31': 3,
 'basis': 23,
 'bihar': 25,
 'police': 95,
 'fir': 59,
 'girlfriend': 64,
 'chakraborty': 34,
 'sushants': 132,
 'fath

In [17]:
c_new_vect = vect1.transform(doc2_)

In [18]:
print ("Text Present at ",c_new_vect.toarray())

Text Present at  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
print ("original indexes", vect1.get_feature_names() )

original indexes ['14', '15', '25', '31', '34', 'according', 'account', 'accountant', 'accounts', 'accused', 'actor', 'actors', 'agency', 'agencys', 'alleged', 'also', 'angle', 'appear', 'ask', 'asked', 'august', 'bandra', 'bank', 'basis', 'behaviour', 'bihar', 'body', 'bodyguard', 'bollywood', 'brother', 'ca', 'case', 'cbi', 'central', 'chakraborty', 'chartered', 'collected', 'complaint', 'connection', 'cook', 'court', 'crore', 'date', 'dead', 'death', 'decide', 'demanded', 'directorate', 'discussed', 'documents', 'driver', 'ecir', 'ed', 'enforcement', 'ex', 'family', 'father', 'filed', 'financial', 'fir', 'first', 'flat', 'flatmate', 'found', 'girlfriend', 'government', 'hearing', 'home', 'house', 'indrajit', 'july', 'june', 'know', 'kotak', 'last', 'late', 'laundering', 'mahindra', 'manager', 'meetings', 'members', 'miranda', 'mitu', 'modi', 'money', 'mumbai', 'named', 'old', 'one', 'others', 'people', 'personal', 'pithani', 'place', 'plea', 'police', 'probe', 'purnea', 'questioning

In [21]:
document1=vect1.get_feature_names()

In [22]:
type(document1)

list

In [27]:
vect2=CountVectorizer()
vect2.fit_transform(doc2_)

<248x137 sparse matrix of type '<class 'numpy.int64'>'
	with 247 stored elements in Compressed Sparse Row format>

In [28]:
document2=vect2.get_feature_names()

In [30]:
similar_words=[]
count=0
for word in document1:
    for word1 in document2:
        if word==word1:
            similar_words.append(word)
            count+=1
print(similar_words)
print(count)

['also', 'asked', 'august', 'bihar', 'case', 'cbi', 'chakraborty', 'court', 'death', 'family', 'father', 'filed', 'fir', 'government', 'hearing', 'mumbai', 'one', 'place', 'plea', 'police', 'probe', 'rajput', 'rhea', 'said', 'singh', 'supreme', 'sushant', 'thursday', 'took', 'transfer']
30
