In [1]:
import cv2
import numpy as np
import os

In [2]:
def make_dir(dirname):
    current_path=os.getcwd()
    path=os.path.join(current_path,dirname)
    if not os.path.exists(path):
        os.makedirs(path)

In [8]:
make_dir('trouser_rot{30}')



In [9]:
directory='C:/Users/Akshay-Laptop/python projects/trouser_rot{30}'
os.chdir(directory)

In [7]:
for i in range(1,101):
    path=r'C:/Users/Akshay-Laptop/python projects/Flipkart_trouser/img_{}.jpg'.format(i)
    img=cv2.imread(path)
    height,width=img.shape[:2]
    rotation_mat=cv2.getRotationMatrix2D((width/2,height/2),-30,1)
    rotated_img=cv2.warpAffine(img,rotation_mat,(width,height))
    cv2.imwrite('trouser_30_{}.jpg'.format(i),rotated_img)
  

In [10]:
for i in range(1,101):
    path=r'C:/Users/Akshay-Laptop/python projects/Flipkart_trouser/img_{}.jpg'.format(i)
    img=cv2.imread(path)
    height,width=img.shape[:2]
    rotation_mat=cv2.getRotationMatrix2D((width/2,height/2),30,1)
    rotated_img=cv2.warpAffine(img,rotation_mat,(width,height))
    cv2.imwrite('trouser30_{}.jpg'.format(i),rotated_img)
  

In [11]:
def increase_brightness(img, value=30):
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv)

    lim = 255 - value
    v[v > lim] = 255
    v[v <= lim] += value

    final_hsv = cv2.merge((h, s, v))
    img = cv2.cvtColor(final_hsv, cv2.COLOR_HSV2BGR)
    return img

In [16]:
path=r'C:/Users/Akshay-Laptop/python projects/Flipkart_trouser/img_4.jpg'
img=cv2.imread(path)
frame = increase_brightness(img, value=30)

In [17]:
frame

array([[[152, 146, 147],
        [152, 146, 147],
        [152, 146, 147],
        ...,
        [140, 133, 135],
        [140, 133, 135],
        [140, 133, 135]],

       [[152, 146, 147],
        [152, 146, 147],
        [152, 146, 147],
        ...,
        [140, 133, 135],
        [140, 133, 135],
        [140, 133, 135]],

       [[152, 146, 147],
        [152, 146, 147],
        [152, 146, 147],
        ...,
        [140, 133, 135],
        [140, 133, 135],
        [140, 133, 135]],

       ...,

       [[182, 176, 177],
        [182, 176, 177],
        [182, 176, 177],
        ...,
        [192, 186, 187],
        [192, 186, 187],
        [192, 186, 187]],

       [[182, 176, 177],
        [182, 176, 177],
        [182, 176, 177],
        ...,
        [192, 186, 187],
        [192, 186, 187],
        [192, 186, 187]],

       [[182, 176, 177],
        [182, 176, 177],
        [182, 176, 177],
        ...,
        [192, 186, 187],
        [192, 186, 187],
        [192, 186, 187]]

In [20]:
cv2.imshow('image',frame)
cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
img

array([[[122, 117, 118],
        [122, 117, 118],
        [122, 117, 118],
        ...,
        [110, 105, 106],
        [110, 105, 106],
        [110, 105, 106]],

       [[122, 117, 118],
        [122, 117, 118],
        [122, 117, 118],
        ...,
        [110, 105, 106],
        [110, 105, 106],
        [110, 105, 106]],

       [[122, 117, 118],
        [122, 117, 118],
        [122, 117, 118],
        ...,
        [110, 105, 106],
        [110, 105, 106],
        [110, 105, 106]],

       ...,

       [[152, 147, 148],
        [152, 147, 148],
        [152, 147, 148],
        ...,
        [162, 157, 158],
        [162, 157, 158],
        [162, 157, 158]],

       [[152, 147, 148],
        [152, 147, 148],
        [152, 147, 148],
        ...,
        [162, 157, 158],
        [162, 157, 158],
        [162, 157, 158]],

       [[152, 147, 148],
        [152, 147, 148],
        [152, 147, 148],
        ...,
        [162, 157, 158],
        [162, 157, 158],
        [162, 157, 158]]

In [12]:
def decrease_brightness(img, value=30):
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv)

    lim = 255 - value
    v[v > lim] = 255
    v[v <= lim] -= value

    final_hsv = cv2.merge((h, s, v))
    img = cv2.cvtColor(final_hsv, cv2.COLOR_HSV2BGR)
    return img

In [13]:
path=r'C:/Users/Akshay-Laptop/python projects/Flipkart_jeans/img_4.jpg'
img=cv2.imread(path)
frame = decrease_brightness(img, value=20)

In [15]:
frame

array([[[102,  98,  99],
        [102,  98,  99],
        [102,  98,  99],
        ...,
        [ 90,  86,  87],
        [ 90,  86,  87],
        [ 90,  86,  87]],

       [[102,  98,  99],
        [102,  98,  99],
        [102,  98,  99],
        ...,
        [ 90,  86,  87],
        [ 90,  86,  87],
        [ 90,  86,  87]],

       [[102,  98,  99],
        [102,  98,  99],
        [102,  98,  99],
        ...,
        [ 90,  86,  87],
        [ 90,  86,  87],
        [ 90,  86,  87]],

       ...,

       [[132, 128, 129],
        [132, 128, 129],
        [132, 128, 129],
        ...,
        [142, 138, 138],
        [142, 138, 138],
        [142, 138, 138]],

       [[132, 128, 129],
        [132, 128, 129],
        [132, 128, 129],
        ...,
        [142, 138, 138],
        [142, 138, 138],
        [142, 138, 138]],

       [[132, 128, 129],
        [132, 128, 129],
        [132, 128, 129],
        ...,
        [142, 138, 138],
        [142, 138, 138],
        [142, 138, 138]]

In [14]:
cv2.imshow('image',frame)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
make_dir('trous_brigh_in')


In [14]:
directory='C:/Users/Akshay-Laptop/python projects/trous_brigh_in'
os.chdir(directory)

In [15]:
for i in range(1,101):
    path=r'C:/Users/Akshay-Laptop/python projects/Flipkart_trouser/img_{}.jpg'.format(i)
    img=cv2.imread(path)
    frame = increase_brightness(img, value=30)
    cv2.imwrite('Bright_inc_t{}.jpg'.format(i),frame)
  

In [17]:
make_dir('trous_brigh_dec')

In [19]:
directory='C:/Users/Akshay-Laptop/python projects/trous_brigh_dec'
os.chdir(directory)

In [20]:
for i in range(1,101):
    path=r'C:/Users/Akshay-Laptop/python projects/Flipkart_trouser/img_{}.jpg'.format(i)
    img=cv2.imread(path)
    frame = decrease_brightness(img, value=20)
    cv2.imwrite('Bright_dec_t{}.jpg'.format(i),frame)
  

In [21]:
make_dir('trous_flip')

In [22]:
directory='C:/Users/Akshay-Laptop/python projects/trous_flip'
os.chdir(directory)

In [23]:
for i in range(1,101):
    path=r'C:/Users/Akshay-Laptop/python projects/Flipkart_trouser/img_{}.jpg'.format(i)
    img=cv2.imread(path)
    frame = cv2.flip(img,1)
    cv2.imwrite('flip_t{}.jpg'.format(i),frame)
  

In [24]:
make_dir('trous_sharpened')

In [26]:
directory='C:/Users/Akshay-Laptop/python projects/trous_sharpened'
os.chdir(directory)

In [27]:
for i in range(1,101):
    path=r'C:/Users/Akshay-Laptop/python projects/Flipkart_trouser/img_{}.jpg'.format(i)
    img=cv2.imread(path)
    kernel_sharpening=np.array([[-1,-1,-1],
                               [-1,10,-1],
                               [-1,-1,-1]])
    sharpened=cv2.filter2D(img,-1,kernel_sharpening)
    
    cv2.imwrite('sharpen_t{}.jpg'.format(i),sharpened)
  